---
toc: true
format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
    other-links:
      - text: StreamFind
        href: https://odea-project.github.io/StreamFind/
        icon: github
    html-math-method: katex
    theme: journal
    code-tools: true
    anchor-sections: true
    code-fold: true
    code-overflow: scroll
    code-line-numbers: false
    code-copy: true
    cap-location: top
    self-contained: true
    embed-resources: true
    toc: true
    toc-location: left
execute:
  warning: false
params:
  engine_rds: "engine_rds.rds"
---

```{r}
#| include: false

options(
  DT.options = list(
    dom = "lfrtip",
    autoWidth = TRUE,
    pageLength = 10,
    lengthMenu = c(10, 20, 50, 75, 100),
    initComplete = htmlwidgets::JS(
      "function(settings, json) {",
      "$(this.api().table().body()).css({'font-size': '12px'});",
      "$(this.api().table().body()).css({'white-space': 'nowrap'});",
      "}"
    )
  )
)

packages <- c("knitr", "kableExtra", "data.table", "DT", "magrittr", "ggplot2", "plotly")
for (pkg in packages) {
  if (requireNamespace(pkg, quietly = TRUE)) {
    library(pkg, character.only = TRUE)
  } else {
    warning(paste("Package", pkg, "is not available"))
  }
}

library(StreamFind)
engine <- readRDS(params$engine_rds)
```

```{r}
#| label: metadata-block
#| output: asis
quarto::write_yaml_metadata_block(
  title = engine$Metadata[["name"]],
  author = engine$Metadata[["author"]],
  date = engine$Metadata[["date"]]
)
```

# Analyses

```{r}
DT::datatable(info(engine$Analyses))
```

<br>
<br>

```{r}
plot_spectra_tic(
  engine$Analyses,
  levels = 1,
  interactive = TRUE,
  colorBy = "replicates",
  title = "Total Ion Chromatograms (TICs)"
)
```

<br>
<br>
