---
title: "Non-target Screening"
author: "Ricardo Cunha"
date: "`r format(Sys.time(), '%d %B, %Y')`"
toc: true
format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
    other-links:
      - text: StreamFind
        href: https://odea-project.github.io/StreamFind/
        icon: github
    html-math-method: katex
    theme: journal
    code-tools: true
    anchor-sections: true
    code-fold: true
    code-overflow: scroll
    code-line-numbers: false
    code-copy: true
    cap-location: top
    self-contained: true
    embed-resources: true
    toc: true
    toc-location: left
execute:
  warning: false
editor_options: 
  chunk_output_type: console
---

# Setup

```{r}
#| include: false
options(DT.options = list(dom = "lfrtip", autoWidth = TRUE, pageLength = 10, lengthMenu = c(10, 20, 50, 75, 100),
  initComplete = htmlwidgets::JS(
    "function(settings, json) {",
    "$(this.api().table().body()).css({'font-size': '12px'});",
    "$(this.api().table().body()).css({'white-space': 'nowrap'});",
    "}"
  )
))

library(knitr)
library(kableExtra)
library(data.table)
library(DT)
library(magrittr)
library(ggplot2)
library(plotly)
library(StreamFind)
```

# Resources

```{r}
#| include: false
ms_files <- StreamFindData::get_ms_file_paths()
ms_files <- ms_files[grepl("blank|influent|o3sw", ms_files)]
ms_files_df <- data.frame(
  "file" = ms_files,
  "replicate" = c(
    rep("blank_neg", 3),
    rep("blank_pos", 3),
    rep("in_neg", 3),
    rep("in_pos", 3),
    rep("out_neg", 3),
    rep("out_pos", 3)
  ),
  "blank" = c(
    rep("blank_neg", 3),
    rep("blank_pos", 3),
    rep("blank_neg", 3),
    rep("blank_pos", 3),
    rep("blank_neg", 3),
    rep("blank_pos", 3)
  )
)

db <- StreamFindData::get_ms_tof_spiked_chemicals_with_ms2()
cols <- c("name", "formula", "mass", "rt", "fragments", "tag")
db <- db[, cols, with = FALSE]
dbis <- db[grepl("IS", db$tag), ]
dbsus <- db[!grepl("IS", db$tag), ]

path <- "C:/Users/apoli/Documents/example_ms_files"
ms_files_complete <- list.files(path, pattern = ".mzML", full.names = TRUE)
```

# Engine

```{r}
#| code-fold: show
ms <- MassSpecEngine$new(analyses = ms_files)
ms$add_replicate_names(ms_files_df$replicate)
ms$add_blank_names(ms_files_df$blank)
ms$Metadata["name"] <- "nts_dev"
```

# Workflow

```{r}
nta_workflow <- list(
  StreamFind::MassSpecMethod_FindFeatures_openms(
    noiseThrInt = 1000,
    chromSNR = 4,
    chromFWHM = 8,
    mzPPM = 15,
    reEstimateMTSD = FALSE,
    traceTermCriterion = "sample_rate",
    traceTermOutliers = 10,
    minSampleRate = 0.4,
    minTraceLength = 5,
    maxTraceLength = -1,
    widthFiltering = "auto", #auto
    minFWHM = 3,
    maxFWHM = 35,
    traceSNRFiltering = TRUE,
    localRTRange = 4,
    localMZRange = 0,
    isotopeFilteringModel = "none",
    MZScoring13C = FALSE,
    useSmoothedInts = FALSE,
    intSearchRTWindow = 3,
    useFFMIntensities = FALSE,
    verbose = FALSE
  ),
  StreamFind::MassSpecMethod_CalculateFeaturesQuality_StreamFind(
    filtered = FALSE,
    rtExpand = 4,
    mzExpand = 0.002,
    minPeakWidth = 10,
    maxPeakWidth = 25,
    minTracesIntensity = 500,
    minNumberTraces = 5,
    baseCut = 0
  ),
  StreamFind::MassSpecMethod_AnnotateFeatures_StreamFind(
    rtWindowAlignment = 0.3,
    maxIsotopes = 8,
    maxCharge = 2,
    maxGaps = 1
  ),
  StreamFind::MassSpecMethod_GroupFeatures_openms(
    rtalign = FALSE,
    maxAlignRT = 10,
    maxAlignMZ = 0.008,
    maxGroupRT = 10,
    maxGroupMZ = 0.008
  ),
  StreamFind::MassSpecMethod_FilterFeatures_StreamFind(
    excludeIsotopes = TRUE,
    excludeAdducts = TRUE
  ),
  StreamFind::MassSpecMethod_FilterFeatures_StreamFind(
    minSnRatio = 4,
    minGaussianFit = 0.4,
    conservative = TRUE
  ),
  StreamFind::MassSpecMethod_FillFeatures_StreamFind(
    withinReplicate = FALSE,
    filtered = FALSE,
    rtExpand = 2,
    mzExpand = 0.005,
    minPeakWidth = 10,
    maxPeakWidth = 25,
    minTracesIntensity = 500,
    minNumberTraces = 5,
    minIntensity = 4000,
    baseCut = 0.01,
    maxSearchWindow = 4,
    minSignalToNoiseRatio = 4,
    minGaussianFit = 0.4
  ),
  StreamFind::MassSpecMethod_FindInternalStandards_StreamFind(
    database = dbis,
    ppm = 15,
    sec = 15
  ),
  StreamFind::MassSpecMethod_CorrectMatrixSuppression_TiChri(
    mpRtWindow = 10,
    istdAssignment = "nearest",
    istdRtWindow = 50,
    istdN = 2
  ),
  StreamFind::MassSpecMethod_FilterFeatures_StreamFind(
    correctIntensity = TRUE,
    blankThreshold = 5,
    conservative = FALSE
  ),
  StreamFind::MassSpecMethod_FilterFeatures_StreamFind(
    minSnRatio = 4,
    minGaussianFit = 0.4,
    conservative = FALSE,
  ),
  StreamFind::MassSpecMethod_FilterFeatures_StreamFind(
    correctIntensity = TRUE,
    minIntensity = 4000,
    conservative = FALSE,
  ),
  StreamFind::MassSpecMethod_FilterFeatures_StreamFind(
    correctIntensity = TRUE,
    maxDeviationInReplicate = 30,
    minAbundanceInReplicate = 3
  ),
  StreamFind::MassSpecMethod_LoadFeaturesMS1_StreamFind(
    rtWindow = c(-2, 2),
    mzWindow = c(-1, 6),
    mzClust = 0.008,
    presence = 0.8,
    minIntensity = 250,
    filtered = FALSE
  ),
  StreamFind::MassSpecMethod_LoadFeaturesMS2_StreamFind(
    isolationWindow = 1.3,
    mzClust = 0.008,
    presence = 0.3,
    minIntensity = 10,
    filtered = TRUE
  ),
  # StreamFind::MassSpecMethod_FilterFeaturesMS2_native(
  #   top = 25,
  #   relMinIntensity = 0.05,
  #   blankClean = TRUE,
  #   mzClust = 0.008,
  #   blankPresenceThreshold = 0.8,
  #   globalPresenceThreshold = 0.3
  # ),
  StreamFind::MassSpecMethod_SuspectScreening_StreamFind(
    database = dbsus,
    ppm = 10,
    sec = 15,
    ppmMS2 = 20,
    mzrMS2 = 0.008,
    minCusiness = 0.7,
    minFragments = 3,
    filtered = FALSE
  ),
  StreamFind::MassSpecMethod_GenerateCompounds_metfrag(
    method = "CL",
    timeout = 300,
    timeoutRetries = 5,
    errorRetries = 5,
    topMost = 5,
    dbRelMzDev = 10,
    fragRelMzDev = 20,
    fragAbsMzDev = 0.008,
    adduct = character(),
    database = "comptox",
    extendedPubChem = "auto",
    chemSpiderToken = "",
    scoreTypes = patRoon::compoundScorings("metfrag", "comptox", onlyDefault = TRUE)$name,
    scoreWeights = 1,
    preProcessingFilters = c("UnconnectedCompoundFilter", "IsotopeFilter"),
    postProcessingFilters = c("InChIKeyFilter"),
    maxCandidatesToStop = 100
  )
)

nta_workflow <- Workflow(nta_workflow)
```

# Run Workflow

```{r}
ms$Workflow <- nta_workflow[1:16]

# cache_cats <- .info_cache_rds()$category
# cache_cats <- cache_cats[grepl("Fill", cache_cats)]
# .clear_cache_rds(cache_cats)

ms$run_workflow()
```

# Dev

```{r}

ms$NonTargetAnalysisResults@feature_list[[11]]
ana <- ms$Analyses

View(fl[, c("feature", "annotation")])


plot_suspects(ms$NonTargetAnalysisResults, analyses = 11)

get_suspects(ms$NonTargetAnalysisResults, analyses = 11)$fragments


fl <- rcpp_nts_load_features_ms2(
  ms$NonTargetAnalysisResults$analyses_info[1, ],
  ms$NonTargetAnalysisResults$spectra_headers[1],
  ms$NonTargetAnalysisResults$feature_list[1],
  filtered = TRUE,
  minTracesIntensity = 10,
  isolationWindow = 1.3,
  mzClust = 0.008,
  presence = 0.3
)

plot_groups_overview(ms$NonTargetAnalysisResults, mass = dbis, legendNames = TRUE)


plot_features_ms2(ms$NonTargetAnalysisResults, analyses = 11, mass = dbis, legendNames = TRUE, filtered = TRUE)

plot_features(ms$NonTargetAnalysisResults, analyses = 4, mass = dbis, legendNames = TRUE)

map_components(ms$NonTargetAnalysisResults, analyses = 4, mass = dbis, legendNames = TRUE)


get_features(ms$NonTargetAnalysisResults, analyses = 4, mass = dbis)


fl_temp <- ms$NonTargetAnalysisResults$feature_list[4:5]
fl_temp <- lapply(fl_temp, function(z) z[order(mz, decreasing = TRUE), ])


res <- rcpp_nts_fill_features(
  ms$NonTargetAnalysisResults$analyses_info,
  ms$NonTargetAnalysisResults$spectra_headers,
  ms$NonTargetAnalysisResults$feature_list,
  withinReplicate = FALSE,
  filtered = FALSE,
  rtExpand = 2,
  mzExpand = 0.005,
  minPeakWidth = 10,
  maxPeakWidth = 25,
  minTracesIntensity = 500,
  minNumberTraces = 5,
  minIntensity = 4000,
  baseCut = 0.01,
  maxSearchWindow = 4,
  minSignalToNoiseRatio = 4,
  minGaussianFit = 0.4
)







fl <- rcpp_nts_annotate_features(
  fl_temp,
  rtWindowAlignment = 0.3,
  maxIsotopes = 8,
  maxCharge = 2,
  maxGaps = 1
)

identical(fl_temp, fl)

View(rbindlist(fl$`01_tof_ww_is_pos_blank-r001`$annotation))

# fl <- rcpp_nts_calculate_features_quality_v2(
#   ms$get_analysis_names()[1:2],
#   ms$get_files()[1:2],
#   ms$NonTargetAnalysisResults@spectra_headers[1:2],
#   ms$NonTargetAnalysisResults$feature_list[1:2],
#   TRUE,
#   rtExpand = 2,
#   mzExpand = 0.002,
#   minPeakWidth = 10,
#   maxPeakWidth = 25,
#   minTracesIntensity = 500,
#   minNumberTraces = 5,
#   baseCut = 0
# )





```


<br>  
<br>  
