---
title: 'Fusion of Mass Spectrometry and Raman Spectroscopy Data Case Study 2'
subtitle: |
  | Detection of quality deviations in paracetamol products
  | <br>
author:
  name: Ricardo Cunha
  email: cunha@iuta.de
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    fig_caption: true
    toc: true
    number_sections: true
    toc_float: true
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Fusion of Mass Spectrometry and Raman Spectroscopy Data}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(magrittr)
library(ggplot2)
library(plotly)
library(data.table)
library(StreamFind)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.align = "center", fig.width = 9, results = "asis", comment = "")

main_dir <- "C:/Users/apoli/Documents/iSoft/Paracetamol"

ms_dir <- paste0(main_dir, "/ms/mzml")

ms_dir_extra <- paste0(main_dir, "/ms/extra/mzml")

ms_files <- list.files(ms_dir, pattern = ".mzML", full.names = TRUE)

ms_files_extra <- list.files(ms_dir_extra, pattern = ".mzML", full.names = TRUE)

raman_dir <- paste0(main_dir, "/raman")

raman_dir_extra <- paste0(main_dir, "/raman/extra")

raman_files <- list.files(raman_dir, pattern = ".asc", full.names = TRUE)

raman_files_extra <- list.files(raman_dir_extra, pattern = ".asc", full.names = TRUE)
```

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

<br>

<br>

***

# Introduction

# Pre-processing

## MS

```{r ms-setup, include=FALSE}
ms <- MassSpecEngine$new(files = ms_files, headers = list(name = "BSA Quality Evaluation Project"))

ms$add_replicate_names(
  c(rep("fiz_a1", 3),
    rep("fiz_a2", 3),
    rep("fiz_a3", 3),
    rep("fiz_b1", 3),
    rep("fiz_b2", 3),
    rep("fiz_b3", 3),
    rep("fiz_c1", 3),
    rep("fiz_c2", 3),
    rep("fiz_c3", 3),
    rep("fiz_caff1", 3),
    rep("fiz_caff2", 3),
    rep("fiz_caff3", 3),
    rep("fiz_ass1", 3),
    rep("fiz_ass2", 3),
    rep("fiz_ass3", 3),
    rep("fiz_d1", 3),
    rep("fiz_d2", 3),
    rep("fiz_d3", 3),
    rep("fiz_acid1", 3),
    rep("fiz_acid2", 3),
    rep("fiz_acid3", 3),
    rep("ass_n_1", 3),
    rep("ass_n_2", 3),
    rep("ass_n_3", 3),
    rep("ass_1", 3),
    rep("ass_2", 3),
    rep("ass_3", 3),
    rep("caff_1", 3),
    rep("caff_2", 3),
    rep("caff_3", 3),
    rep("par_1", 3),
    rep("par_2", 3),
    rep("par_3", 3),
    rep("blank", 23)
  )
)

ms <- ms$subset_analyses(analyses = c(1:63, 73:99, 118:121))

ms$add_blank_names(rep("blank", 94))

ms$load_spectra()
```

```{r ms-overview, echo=FALSE}
ov <- ms$get_overview()[, 1:3]
setorder(ov, replicate)
ov$description <- c(
  rep("Aspirine standard", 9),
  rep("Reference background", 4),
  rep("Caffein", 9),
  rep("Paracetamol product", 9),
  rep("Paracetamol with acetic acid", 9),
  rep("Paracetamol with aspirine", 9),
  rep("Paracetamol product", 9),
  rep("Paracetamol product", 9),
  rep("Paracetamol with caffein", 9),
  rep("Paracetamol product", 9),
  rep("Paracetamol standard", 9)
)

kable(ov, caption = "Overview of MS analyses and respective analysis replicate groups and blanks.") %>%
kable_styling(font_size = 12, bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = TRUE) %>%
scroll_box(width = "100%", height = "400px")
```

```{r plot-ms-tic, fig.cap="Total ion chromatogram (TIC) for each analysis replicate."}
ms$plot_spectra_tic(colorBy = "replicates")
```

```{r ms-workflow}
ms_workflow_settings <- list(
  Settings_bin_spectra_StreamFind(bins = list("rt" = 5, "mz" = 2), refBinAnalysis = 1),
  Settings_normalize_spectra_minmax(),
  Settings_average_spectra_StreamFind(),
  Settings_subtract_blank_spectra_StreamFind(negativeToZero = TRUE),
  Settings_normalize_spectra_blockweight()
)

ms$add_settings(ms_workflow_settings)

ms$print_workflow()
```

```{r ms-run-workflow}
ms$run_workflow()
```

```{r plot-ms-spectra, fig.cap="Pre-processed spectra for each analysis. Retention time dimension in he created bins is collapsed for each mass-to-charge ratio"}
ms$plot_spectra()
```

```{r ms-spectra}
ms$get_spectra()[1:10, ]
```

## Raman

```{r raman-setup, include=FALSE}
raman <- RamanEngine$new(raman_files)

raman$add_replicate_names(
  c(
    rep("ass_1", 3),
    rep("ass_2", 3),
    rep("ass_3", 3),
    rep("caff_1", 3),
    rep("caff_2", 3),
    rep("caff_3", 3),
    rep("blank", 9),
    rep("fiz_c1", 3),
    rep("fiz_c2", 3),
    rep("fiz_c3", 3),
    rep("fiz_ass_n_1", 3),
    rep("fiz_ass_n_2", 3),
    rep("fiz_ass_n_3", 3),
    rep("fiz_ass1", 3),
    rep("fiz_ass2", 3),
    rep("fiz_ass3", 3),
    rep("fiz_caff1", 3),
    rep("fiz_caff2", 3),
    rep("fiz_caff3", 3),
    rep("fiz_a1", 3),
    rep("fiz_a2", 3),
    rep("fiz_a3", 3),
    rep("fiz_d1", 3),
    rep("fiz_d2", 3),
    rep("fiz_d3", 3),
    rep("fiz_b1", 3),
    rep("fiz_b2", 3),
    rep("fiz_b3", 3),
    rep("background", 4),
    rep("fiz_acid1", 3),
    rep("fiz_acid2", 3),
    rep("fiz_acid3", 3),
    rep("par_1", 3),
    rep("par_odd", 3),
    rep("par_3", 3),
    rep("par_2", 3),
    rep("cali_150_mgml", 9),
    rep("cali_010_mgml", 9),
    rep("cali_025_mgml", 9),
    rep("cali_050_mgml", 9),
    rep("cali_075_mgml", 9),
    rep("background", 4)
  )
)

ramanQuant <- raman$subset_analyses(analyses = c(19:27, 116:160))
ramanQuant$add_blank_names(rep("blank", 54))

raman <- raman$subset_analyses(analyses = c(1:36, 46:90, 95:106, 110:115))
raman$add_blank_names(rep("blank", 99))
```

```{r plot-raman-raw, fig.cap="Raw averaged Raman spectra for each analysis replicate."}
raman$plot_spectra(colorBy = "replicates")
```

```{r raman-workflow}
raman_workflow_settings <- list(
  Settings_average_spectra_StreamFind(),
  Settings_subtract_blank_spectra_StreamFind(),
  Settings_smooth_spectra_savgol(fl = 21, forder = 4, dorder = 0),
  Settings_delete_spectra_section_StreamFind(list("shift" = c(-100, 350))),
  Settings_delete_spectra_section_StreamFind(list("shift" = c(1800, 2500))),
  Settings_correct_spectra_baseline_airpls(lambda = 45, differences = 1, itermax = 30),
  Settings_normalize_spectra_minmax(),
  Settings_normalize_spectra_blockweight()
)

raman$add_settings(raman_workflow_settings)

raman$print_workflow()
```

```{r raman-run-workflow}
raman$run_workflow()
```

```{r plot-raman-spectra, fig.cap="Pre-processed Raman spectra for analysis replicate."}
raman$plot_spectra()
```

```{r raman-spectra}
raman$get_spectra()[1:10, ]
```

# Fusion

```{r fusion}
rSpec <- raman$get_spectra()
rSpec <- rSpec[order(rSpec$replicate), ]
mrSpec <- matrix(rSpec$intensity, nrow = length(unique(rSpec$replicate)), ncol = length(unique(rSpec$shift)), byrow = TRUE, dimnames = list(as.character(unique(rSpec$replicate)), as.character(round(unique(rSpec$shift), digits = 1))))

mSpec <- ms$get_spectra()
mSpec <- mSpec[order(mSpec$replicate), ]
mmSpec <- matrix(mSpec$intensity, nrow = length(unique(mSpec$replicate)), ncol = length(unique(mSpec$bins)), byrow = TRUE, dimnames = list(unique(mSpec$replicate), unique(mSpec$bins)))

fusedMat <- cbind(mmSpec, mrSpec)

# Matrix is mean centered but not scaled
fusedMat <- mdatools::prep.autoscale(fusedMat, center = TRUE, scale = FALSE)
```

```{r plot-fused, include=FALSE, fig.cap="Fused spectra."}
cl <- StreamFind:::.get_colors(rownames(fusedMat))
fig <- plot_ly()
xVal <- seq_len(length(fusedMat[1, ]))
for (i in seq_len(nrow(fusedMat))) {
  fig <- fig %>% add_trace(
    x = xVal,
    y = fusedMat[i, ],
    type = "scatter", mode = "lines",
    line = list(width = 0.5, color = unname(cl[i])),
    name = names(cl)[i],
    legendgroup = names(cl)[i],
    showlegend = TRUE
  )
}
xaxis <- list(
  linecolor = toRGB("black"),
  linewidth = 2, title = "Bins",
  titlefont = list(size = 12, color = "black")
)
yaxis <- list(
  linecolor = toRGB("black"),
  linewidth = 2, title = "Intensity",
  titlefont = list(size = 12, color = "black")
)
fig <- fig %>% plotly::layout(xaxis = xaxis, yaxis = yaxis)
fig
```

# Statistic analysis

```{r extra-data, include=FALSE}
ms_extra <- MassSpecEngine$new(files = ms_files_extra[c(5:40, 49:60)])

ms_extra$add_replicate_names(
  c(
    rep("fiz_e01", 3),
    rep("fiz_e02", 3),
    rep("fiz_e03", 3),
    rep("fiz_e04", 3),
    rep("fiz_e05", 3),
    rep("fiz_e06", 3),
    rep("fiz_e07", 3),
    rep("fiz_e08", 3),
    rep("fiz_e09", 3),
    rep("fiz_e10", 3),
    rep("fiz_e11", 3),
    rep("fiz_e12", 3),
    rep("blank", 12)
  )
)

ms_extra$add_blank_names(rep("blank", 48))

ms_extra$load_spectra()

ms_extra$add_settings(ms_workflow_settings)

ms_extra$run_workflow()

ms_extra$plot_spectra()
```

## Unsupervised

Principle Components Analysis (PCA) for unsupervised evaluation.

```{r sets-show}
main_set <- fusedMat[c(7:8, 16, 18, 20:21, 25:27), ]
rownames(main_set)

test_set <- fusedMat[c(1:6, 9:15, 17, 19, 22:24, 28:30), ]
rownames(test_set)
```

```{r pca-engine, fig.cap="PCA model (native plot from mdatools R package).", fig.height=9}}
stat <- StatisticEngine$new(data = main_set)
stat$make_model(Settings_make_model_pca_mdatools(ncomp = 2, alpha = 5E-3, gamma = 5E-4))
plot(stat$model)
```

```{r pca-predict, fig.cap="PCA model prediction distances. For more information about the distances plese consult the mdatools guide in https://mdatools.com/docs/pca--distances-and-limits.html."}
stat$predict(test_set)
stat$plot_predicted_distances()
```

## Supervised (classification)

k-nearest neighbors (KNN) for classification.

```{r sets-show-knn}
train_set <- fusedMat[c(grep("1", rownames(fusedMat)), grep("2", rownames(fusedMat))), ]
train_set <- train_set[order(rownames(train_set)), ]
rownames(train_set)

test_set <- fusedMat[grep("3", rownames(fusedMat)), ]
rownames(test_set)
```

```{r knn-classes}
labels <- c(rep("ass", 2), rep("caff", 2), rep("fiz", 2), rep("fiz_acid", 2), rep("fiz_ass", 2),
  rep("fiz", 2), rep("fiz", 2), rep("fiz_caff", 2), rep("fiz", 2), rep("par", 2))
```

```{r knn-classes-show, echo=FALSE}
kable(data.frame(replicate = rownames(train_set), class = labels), caption = "Clss assignment for training set.") %>%
kable_styling(font_size = 12, bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = TRUE) %>%
scroll_box(width = "100%", height = "400px")
```

```{r knn-engine}
stat2 <- StatisticEngine$new(data = train_set)
stat2$add_classes(labels)
stat2$prepare_classification(Settings_prepare_classification_knn(k = 3))
stat2$classify(test_set)
stat2$classification_results
```

# Quantification with Raman

```{r ov-raman-conc, include=FALSE}
ov2 <- ramanQuant$get_overview()[, 1:3]
setorder(ov2, replicate)
ov2$concentration <- as.numeric(c(rep(0, 9), sub(".*?(\\d+).*", "\\1", ov2$replicate[10:nrow(ov2)]))) / 10

kable(ov2, caption = "Overview of Raman analyses for quantification with respective concentration.") %>%
kable_styling(font_size = 12, bootstrap_options = c("striped", "hover", "condensed", "responsive"), fixed_thead = TRUE) %>%
scroll_box(width = "100%", height = "400px")
```

```{r plot-raman-conc-raw, fig.cap="Raw averaged Raman spectra for each analysis replicate."}
ramanQuant$plot_spectra(colorBy = "replicates")
```

```{r raman-conc-workflow}
raman_workflow_settings <- list(
  Settings_average_spectra_StreamFind(),
  Settings_subtract_blank_spectra_StreamFind(),
  Settings_smooth_spectra_savgol(fl = 21, forder = 4, dorder = 0),
  Settings_delete_spectra_section_StreamFind(list("shift" = c(-100, 350))),
  Settings_delete_spectra_section_StreamFind(list("shift" = c(1800, 2500))),
  Settings_correct_spectra_baseline_airpls(lambda = 45, differences = 1, itermax = 30)
)

ramanQuant$add_settings(raman_workflow_settings)

ramanQuant$print_workflow()
```

```{r raman-conc-run-workflow}
ramanQuant$run_workflow()
```

```{r plot-raman-conc-spectra, fig.cap="Pre-processed Raman spectra for analysis replicate."}
ramanQuant$plot_spectra()
```

```{r raman-quant-mat}
rSpecQuant <- ramanQuant$get_spectra()
rSpecQuant <- rSpecQuant[order(rSpecQuant$replicate), ]
mrSpecQuant <- matrix(
  rSpecQuant$intensity,
  nrow = length(unique(rSpecQuant$replicate)),
  ncol = length(unique(rSpecQuant$shift)),
  byrow = TRUE,
  dimnames = list(as.character(unique(rSpecQuant$replicate)), as.character(round(unique(rSpecQuant$shift), digits = 1)))
)
```

```{r, include=FALSE, eval=FALSE}

ramanQuant$plot_spectra_baseline()

library(mdatools)
m1 = mcrals(mrSpecQuant, ncomp = 2)
plotSpectra(m1)


summary(m1)

conc_ov <- ov2[, c(2, 4)]
conc_ov <- unique(conc_ov)

show(head(m1$rescont))

plot(conc_ov$concentration[-1], m1$rescont[, 2], type = "l")

x <- conc_ov$concentration[-1]
y <- m1$rescont[, 2]
linear_model <- lm(x  ~  y)

summary_linear_model <- summary(linear_model)
r_squared <- summary_linear_model$r.squared
r_squared

predict(lm(m1$rescont[, 2] ~ conc_ov$concentration[-1]), data.frame(x = 372.8276, 199, 399, 349), se.fit = TRUE)

predict(linear_model, data.frame(x = c(m1$rescont[, 2], 334)))



new_rescont_value <- 1200  # replace with your actual new value

# Create a data frame with the new value
new_data <- data.frame(y = new_rescont_value)

# Use predict to get the predicted concentration
predicted_concentration <- predict(linear_model, newdata = new_data)

# Print the predicted concentration
print(predicted_concentration)

```

























