---
title: "streamFind"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{streamFind}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction to streamFind

The goal of the streamFind is to boost competences of researchers for data analysis. The focus is the development and assembly of data processing workflows for mass spectrometry (MS) and spectroscopy (e.g., Raman) and the application of the workflows in environmental and quality studies of the water cycle. For the moment, the streamFind can be used via the experimental [streamFind R package](https://github.com/ricardobachertdacunha?tab=repositories) with preliminary back-end framework for mass spectrometry. For more information and usage see article ["streamFind for mass spectrometry with R"](https://ricardobachertdacunha.github.io/streamFind/articles/ms_overview.html).

# Development in progress

The life cycle of the streamFind R package is [experimental](https://lifecycle.r-lib.org/articles/stages.html). Please [contact us](mailto:cunha@iuta.de) for questions, suggestions, issues or collaboration. Besides further development of the R package, a graphical user interface is planned to facilitate data analysis and assembly of workflows. Stay tuned!
