---
title: "Report Peak Finding Merck V3"
subtitle: "Integration in StreamFind and Structural Based Screening"
author: "Ricardo Cunha"
date: "`r format(Sys.time(), '%d %B, %Y')`"
toc: true
format:
  html:
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 300px
      gutter-width: 1.5rem
    other-links:
      - text: StreamFind
        href: https://odea-project.github.io/StreamFind/
        icon: github
    html-math-method: katex
    theme: journal
    code-tools: true
    anchor-sections: true
    code-fold: false
    code-overflow: scroll
    code-line-numbers: false
    code-copy: true
    cap-location: top
    self-contained: true
    embed-resources: true
    toc: true
    toc-location: left
execute:
  warning: false
---

```{r}
#| label: setup
#| include: false

options(DT.options = list(
  dom = "lfrtip",
  autoWidth = TRUE,
  pageLength = 10,
  lengthMenu = c(10, 20, 50, 75, 100),
  initComplete = htmlwidgets::JS(
    "function(settings, json) {",
    "$(this.api().table().body()).css({'font-size': '12px'});",
    "$(this.api().table().body()).css({'white-space': 'nowrap'});",
    "}"
  )
))

simple_table_opt <- list(
  dom = 't',
  paging = FALSE,
  searching = FALSE,
  info = FALSE
)

library(knitr)
library(kableExtra)
library(data.table)
library(DT)
library(magrittr)
library(ggplot2)
library(plotly)
library(StreamFind)

#devtools::load_all()

resources_file <- file.path(
  getwd(),
  "dev",
  "merck_peak_finding",
  "dev_resources.R"
)

if (!file.exists(resources_file)) {
  resources_file <- file.path(
    getwd(),
    "dev_resources.R"
  )
}

project_path <- file.path(dirname(resources_file), "data")
source(resources_file)
```

# Integration in StreamFind

## Engine Setup

```{r}
#| label: merck-cleanup
#| include: false

# file.remove(list.files(project_path, full.names = TRUE))
# fs::dir_delete(project_path)
```

```{r}
#| label: merck-engine-setup

example_key <- "ACC1_28146"
ex_targets <- merck2_db_ex[merck2_db_ex$example %in% example_key, ]
ex_files <- merck2_files_ex$file_path[merck2_files_ex$example %in% example_key]

ms <- DB_MassSpecEngine$new(project_path, files = ex_files)

set_replicate_names(ms$Analyses, c("blank", "sample"))
set_blank_names(ms$Analyses, c("blank", "blank"))
```

```{r}
#| label: merck-inspect-engine

ms
```

## Workflow

```{r}
#| label: merck-workflow

ps_ff <- DB_MassSpecMethod_FindFeatures_native(
  rtWindows = data.frame(rtmin = 300, rtmax = 3400),
  ppmThreshold = 15,
  noiseThreshold = 15,
  minSNR = 3,
  minTraces = 3,
  baselineWindow = 200,
  maxWidth = 250,
  baseQuantile = 0.99,
  debugAnalysis = "",
  debugMZ = 0,
  debugSpecIdx = -1
)

ps_comp <- DB_MassSpecMethod_CreateComponents_native(
  rtWindow = c(-15, 15),
  minCorrelation = 0.5,
  debugRT = 0,
  debugAnalysis = ""
)

ps_annot <- DB_MassSpecMethod_AnnotateComponents_native(
  maxIsotopes = 8,
  maxCharge = 1,
  maxGaps = 1,
  ppm = 10,
  debugComponent = "",
  debugAnalysis = ""
)

ps_bsub <- DB_MassSpecMethod_FeatureBlankSubtraction_native(
  blankThreshold = 5,
  rtExpand = 20,
  mzExpand = 0.005
)

ps_ms1 <- DB_MassSpecMethod_LoadFeaturesMS1_native(
  rtWindow = c(-1, 1),
  mzWindow = c(-1, 6),
  mzClust = 0.008,
  presence = 0.5,
  minIntensity = 50,
  filtered = FALSE
)

ps_ms2 <- DB_MassSpecMethod_LoadFeaturesMS2_native(
  isolationWindow = 1.3,
  mzClust = 0.008,
  presence = 0.5,
  minIntensity = 10,
  filtered = FALSE
)

ms$Workflow = list(ps_ff, ps_comp) #, ps_annot, ps_bsub
```

```{r}
#| label: merck-inspect-workflow

show(ms$Workflow)
```

```{r}
#| label: merck-run-workflow
#| results: "hide"

ms$run_workflow()
```

## Results

```{r}
#| label: merck-inspect-features-count
#| fig-height: 7
#| fig-width: 10

p1 <- plot_features_count(ms$NonTargetAnalysis, filtered = TRUE, groupBy = "replicate") %>%
  plotly::layout(annotations = list(
    list(
      x = 0.2, y = 1, xref = "paper", yref = "paper",
      text = "Before Filtration", showarrow = FALSE,
      font = list(size = 16)
    )
  ))

p2 <- plot_features_count(ms$NonTargetAnalysis, filtered = FALSE, groupBy = "replicate") %>%
  plotly::layout(annotations = list(
    list(
      x = 0.2, y = 1, xref = "paper", yref = "paper",
      text = "After Filtration", showarrow = FALSE,
      font = list(size = 16)
    )
  ))

plotly::subplot(
  p1, p2,
  nrows = 1,
  margin = 0.05,
  shareY = TRUE,
  titleX = TRUE,
  titleY = TRUE
)
```

### Targets

```{r}
#| label: merck-inspect-results
#| fig-height: 10
#| fig-width: 10

plot_features(
  ms$NonTargetAnalysis,
  analyses = 2,
  mz = merck2_db_ex[merck2_db_ex$example %in% example_key, ],
  ppm = 20,
  sec = 60,
  showDetails = TRUE
)
```

### Components

```{r}
#| label: merck-inspect-components

ft_main <- get_features(
  ms$NonTargetAnalysis,
  analyses = 2,
  mz = merck2_db_ex[merck2_db_ex$example %in% example_key, ][7, ]$rt,
  ppm = 20,
  sec = 60,
  filtered = TRUE
)

map_features(
  ms$NonTargetAnalysis,
  analyses = 2,
  groupBy = "feature_component",
  rt = merck2_db_ex[merck2_db_ex$example %in% example_key, ][6, ]$rt,
  sec = 60,
  globalNormalization = TRUE,
  showDetails = FALSE
)

map_features(
  ms$NonTargetAnalysis,
  analyses = 2,
  groupBy = "feature_component",
  rt = 990,
  sec = 60,
  globalNormalization = TRUE,
  showDetails = FALSE
)


16.5 * 60


get_suspects_screening_csv(
  suspects = data.table(
    name = "ACC1_28203",
    rt = 100,
    mol = file.path("E:\\example_ms_files\\peak_finding_files_ex\\merck\\More Data OLED Routine for Ricardo\\ACC1_28203_3.mol")
  ),
  file = file.path("ACC1_28203_suspects.csv")
)


map_features(
  ms$NonTargetAnalysis,
  analyses = 2,
  groupBy = "feature_component",
  components = "FC1_RT615_POS",
  showDetails = TRUE
)
```

# App

```{r}
#| label: run_app
#| eval: false

# project_path <- file.path(getwd(), "dev", "merck_peak_finding", "data")
# ms <- DB_MassSpecEngine$new(project_path)
# ms$run_app()
```
