// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _streamFind_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_extract_eics
Rcpp::List rcpp_extract_eics(Rcpp::List spec, Rcpp::DataFrame targets);
RcppExport SEXP _streamFind_rcpp_extract_eics(SEXP specSEXP, SEXP targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type targets(targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_extract_eics(spec, targets));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_ms_extract_eics_from_dataframe
List rcpp_ms_extract_eics_from_dataframe(DataFrame spec, DataFrame targets);
RcppExport SEXP _streamFind_rcpp_ms_extract_eics_from_dataframe(SEXP specSEXP, SEXP targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type spec(specSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type targets(targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_ms_extract_eics_from_dataframe(spec, targets));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_ms_extract_eics_from_dataframe_2
DataFrame rcpp_ms_extract_eics_from_dataframe_2(List spec, DataFrame targets);
RcppExport SEXP _streamFind_rcpp_ms_extract_eics_from_dataframe_2(SEXP specSEXP, SEXP targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type targets(targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_ms_extract_eics_from_dataframe_2(spec, targets));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_ms_extract_ms2_from_dataframe
List rcpp_ms_extract_ms2_from_dataframe(DataFrame spec, DataFrame targets, double mzClust, bool verbose);
RcppExport SEXP _streamFind_rcpp_ms_extract_ms2_from_dataframe(SEXP specSEXP, SEXP targetsSEXP, SEXP mzClustSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type spec(specSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< double >::type mzClust(mzClustSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_ms_extract_ms2_from_dataframe(spec, targets, mzClust, verbose));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_extract_xics
Rcpp::List rcpp_extract_xics(Rcpp::List spec, Rcpp::DataFrame targets);
RcppExport SEXP _streamFind_rcpp_extract_xics(SEXP specSEXP, SEXP targetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type spec(specSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type targets(targetsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_extract_xics(spec, targets));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_streamFind_rcpp_hello_world", (DL_FUNC) &_streamFind_rcpp_hello_world, 0},
    {"_streamFind_rcpp_extract_eics", (DL_FUNC) &_streamFind_rcpp_extract_eics, 2},
    {"_streamFind_rcpp_ms_extract_eics_from_dataframe", (DL_FUNC) &_streamFind_rcpp_ms_extract_eics_from_dataframe, 2},
    {"_streamFind_rcpp_ms_extract_eics_from_dataframe_2", (DL_FUNC) &_streamFind_rcpp_ms_extract_eics_from_dataframe_2, 2},
    {"_streamFind_rcpp_ms_extract_ms2_from_dataframe", (DL_FUNC) &_streamFind_rcpp_ms_extract_ms2_from_dataframe, 4},
    {"_streamFind_rcpp_extract_xics", (DL_FUNC) &_streamFind_rcpp_extract_xics, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_streamFind(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
