utils::globalVariables(c(
  "AnalysesTable", "AnalysesTable_cell_edit", "AnalysesTable_cells_selected",
  "Class", "ID", "a", "accumulations", "add_analyses_button", "add_header_button",
  "add_workflow_step", "adduct", "adduct_cat", "adduct_mass_error",
  "adduct_time_error", "algorithm", "analyses_info", "analyses_overview_buttons",
  "analyses_ui", "analysis", "annotation", "app_mode_ui", "area",
  "audit_trail", "audit_ui", "author", "avgFun", "b", "basePeakIntensity",
  "basePeakMZ", "blank", "blanks", "body_ui", "br", "capture.output",
  "clear_workflow", "clear_workflow_ui", "clusterMzWindow", "component_feature",
  "compounds", "concentration", "config_ui", "config_ui_cell_edit", "contact",
  "correction", "data", "data_type", "datapath", "dd", "details", "developer",
  "discard_changes", "discard_changes_ui", "div", "dl", "doi", "drift",
  "driftmax", "driftmin", "dt", "eic", "engine", "engine_save_file_ui",
  "explorer_ui", "feature", "file_io", "files", "filled", "filter", "filtered",
  "formulas", "gauss_a", "gauss_f", "gauss_s", "gauss_u", "get_spectra_polarity",
  "group", "groupParam", "has_analyses", "has_results_nts", "hash", "highMZ",
  "id", "idx", "index", "integrate", "intensity", "is_pre", "iso_cat",
  "iso_isotope", "iso_mass_distance_error", "iso_number_carbons",
  "iso_time_error", "istd", "level", "li", "link", "load_sif", "load_workflow",
  "load_workflow_ui", "loading_spinner", "lowMZ", "mass", "merged",
  "metadata_list", "metadata_ui", "minIntensityPost", "minIntensityPre",
  "mobilitymax", "mobilitymin", "modifyList", "mp", "ms1", "ms2", "msLevel",
  "mz", "mzmax", "mzmin", "name", "new_header_name", "new_header_value",
  "noise", "notes_analyses", "object.size", "open_help_modal", "p", "parameters",
  "path", "peak", "peakGroupsMatrix", "peaksCount", "polarity", "preGroupParam",
  "pre_mz", "precursor", "precursorMZ", "quality", "rank_workflow_names",
  "read.csv", "reference", "remove_all_analyses", "remove_selected_analyses",
  "replicates", "required", "reset_engine", "reset_engine_button",
  "reset_method", "restart_app", "results", "results_ui", "ret", "retentionTime",
  "retmax", "retmin", "roiScales", "rt", "rtalign", "rtmax", "rtmin",
  "run_workflow", "run_workflow_ui", "save_engine", "save_engine_button",
  "save_engine_button_file", "save_workflow", "save_workflow_ui",
  "scanWindowLowerLimit", "scanWindowUpperLimit", "selected_method_details",
  "self", "seqNum", "set_wdir_button", "settings_selector", "sidebar_ui", "sn",
  "software", "span", "spectra_headers", "strong", "style", "suspects", "tags",
  "topMost", "totIonCurrent", "type", "ul", "update_method", "value",
  "warningMenu", "wdir", "width", "workflow", "workflow_settings", "workflow_ui",
  "xVal"
))