# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_nts_find_features2 <- function(info, spectra_headers, rtWindowsMin, rtWindowsMax, ppmThreshold = 15.0, noiseThreshold = 15.0, minSNR = 3.0, minTraces = 3L, baselineWindow = 200.0, maxWidth = 100.0, baseQuantile = 0.10, debugAnalysis = "", debugMZ = 0.0, debugSpecIdx = -1L) {
    .Call(`_StreamFind_rcpp_nts_find_features2`, info, spectra_headers, rtWindowsMin, rtWindowsMax, ppmThreshold, noiseThreshold, minSNR, minTraces, baselineWindow, maxWidth, baseQuantile, debugAnalysis, debugMZ, debugSpecIdx)
}

rcpp_nts_load_features_ms1_2 <- function(info, spectra_headers, feature_list, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence) {
    .Call(`_StreamFind_rcpp_nts_load_features_ms1_2`, info, spectra_headers, feature_list, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence)
}

rcpp_nts_load_features_ms2_2 <- function(info, spectra_headers, feature_list, filtered, minTracesIntensity, isolationWindow, mzClust, presence) {
    .Call(`_StreamFind_rcpp_nts_load_features_ms2_2`, info, spectra_headers, feature_list, filtered, minTracesIntensity, isolationWindow, mzClust, presence)
}

rcpp_nts_create_components <- function(info, spectra_headers, feature_list, rtWindow, minCorrelation = 0.8, debugRT = 0.0, debugAnalysis = "") {
    .Call(`_StreamFind_rcpp_nts_create_components`, info, spectra_headers, feature_list, rtWindow, minCorrelation, debugRT, debugAnalysis)
}

rcpp_nts_annotate_components <- function(info, spectra_headers, feature_list, maxIsotopes = 5L, maxCharge = 1L, maxGaps = 1L, debugComponent = "", debugAnalysis = "") {
    .Call(`_StreamFind_rcpp_nts_annotate_components`, info, spectra_headers, feature_list, maxIsotopes, maxCharge, maxGaps, debugComponent, debugAnalysis)
}

rcpp_nts_group_features_2 <- function(info, spectra_headers, feature_list, method = "obi_warp", internal_standards_list = NULL, rtDeviation = 5.0, ppm = 5.0, minSamples = 1L, binSize = 5.0, debug = FALSE, debugRT = 0.0) {
    .Call(`_StreamFind_rcpp_nts_group_features_2`, info, spectra_headers, feature_list, method, internal_standards_list, rtDeviation, ppm, minSamples, binSize, debug, debugRT)
}

rcpp_fill_bin_spectra <- function(spectra, bin_mat, bins, overlap = 0, summaryFunction = "max") {
    .Call(`_StreamFind_rcpp_fill_bin_spectra`, spectra, bin_mat, bins, overlap, summaryFunction)
}

rcpp_ms_cluster_spectra <- function(spectra, mzClust = 0.005, presence = 0.8, verbose = FALSE) {
    .Call(`_StreamFind_rcpp_ms_cluster_spectra`, spectra, mzClust, presence, verbose)
}

rcpp_parse_ms_analysis <- function(file_path) {
    .Call(`_StreamFind_rcpp_parse_ms_analysis`, file_path)
}

rcpp_parse_ms_spectra_headers <- function(file_path) {
    .Call(`_StreamFind_rcpp_parse_ms_spectra_headers`, file_path)
}

rcpp_parse_ms_chromatograms_headers <- function(file_path) {
    .Call(`_StreamFind_rcpp_parse_ms_chromatograms_headers`, file_path)
}

rcpp_parse_ms_spectra <- function(analysis, levels, targets, minIntensityMS1, minIntensityMS2) {
    .Call(`_StreamFind_rcpp_parse_ms_spectra`, analysis, levels, targets, minIntensityMS1, minIntensityMS2)
}

rcpp_parse_ms_chromatograms <- function(analysis, idx) {
    .Call(`_StreamFind_rcpp_parse_ms_chromatograms`, analysis, idx)
}

rcpp_ms_load_features_eic <- function(analyses_names, analyses_files, headers, features, filtered, rtExpand, mzExpand, minTracesIntensity) {
    .Call(`_StreamFind_rcpp_ms_load_features_eic`, analyses_names, analyses_files, headers, features, filtered, rtExpand, mzExpand, minTracesIntensity)
}

rcpp_nts_load_features_eic <- function(info, spectra_headers, feature_list, filtered = FALSE, rtExpand = 0, mzExpand = 0, minTracesIntensity = 0) {
    .Call(`_StreamFind_rcpp_nts_load_features_eic`, info, spectra_headers, feature_list, filtered, rtExpand, mzExpand, minTracesIntensity)
}

rcpp_ms_load_features_ms1 <- function(analyses_names, analyses_files, headers, features, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence) {
    .Call(`_StreamFind_rcpp_ms_load_features_ms1`, analyses_names, analyses_files, headers, features, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence)
}

rcpp_nts_load_features_ms1 <- function(info, spectra_headers, feature_list, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence) {
    .Call(`_StreamFind_rcpp_nts_load_features_ms1`, info, spectra_headers, feature_list, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence)
}

rcpp_ms_load_features_ms2 <- function(analyses_names, analyses_files, headers, features, filtered, minTracesIntensity, isolationWindow, mzClust, presence) {
    .Call(`_StreamFind_rcpp_ms_load_features_ms2`, analyses_names, analyses_files, headers, features, filtered, minTracesIntensity, isolationWindow, mzClust, presence)
}

rcpp_nts_load_features_ms2 <- function(info, spectra_headers, feature_list, filtered, minTracesIntensity, isolationWindow, mzClust, presence) {
    .Call(`_StreamFind_rcpp_nts_load_features_ms2`, info, spectra_headers, feature_list, filtered, minTracesIntensity, isolationWindow, mzClust, presence)
}

rcpp_nts_calculate_features_quality <- function(info, spectra_headers, feature_list, filtered = FALSE, rtExpand = 0, mzExpand = 0, minPeakWidth = 6, maxPeakWidth = 30, minTracesIntensity = 0, minNumberTraces = 5, baseCut = 0) {
    .Call(`_StreamFind_rcpp_nts_calculate_features_quality`, info, spectra_headers, feature_list, filtered, rtExpand, mzExpand, minPeakWidth, maxPeakWidth, minTracesIntensity, minNumberTraces, baseCut)
}

rcpp_nts_annotate_features <- function(feature_list, rtWindowAlignment = 0.3, maxIsotopes = 5L, maxCharge = 1L, maxGaps = 1L) {
    .Call(`_StreamFind_rcpp_nts_annotate_features`, feature_list, rtWindowAlignment, maxIsotopes, maxCharge, maxGaps)
}

rcpp_nts_fill_features <- function(info, spectra_headers, feature_list, withinReplicate = FALSE, filtered = FALSE, rtExpand = 0, mzExpand = 0, minPeakWidth = 6, maxPeakWidth = 30, minTracesIntensity = 0, minNumberTraces = 4, minIntensity = 0, baseCut = 0, maxSearchWindow = 5, minSignalToNoiseRatio = 3, minGaussianFit = 0.5) {
    .Call(`_StreamFind_rcpp_nts_fill_features`, info, spectra_headers, feature_list, withinReplicate, filtered, rtExpand, mzExpand, minPeakWidth, maxPeakWidth, minTracesIntensity, minNumberTraces, minIntensity, baseCut, maxSearchWindow, minSignalToNoiseRatio, minGaussianFit)
}

rcpp_nts_find_features <- function(info, spectra_headers, rtWindowsMin, rtWindowsMax, resolution_profile, noiseThreshold = 15.0, minSNR = 3.0, minTraces = 3L, baselineWindow = 200.0, maxWidth = 100.0) {
    .Call(`_StreamFind_rcpp_nts_find_features`, info, spectra_headers, rtWindowsMin, rtWindowsMax, resolution_profile, noiseThreshold, minSNR, minTraces, baselineWindow, maxWidth)
}

rcpp_decode_eic_data <- function(base64_encoded) {
    .Call(`_StreamFind_rcpp_decode_eic_data`, base64_encoded)
}

rcpp_parse_asc_file <- function(file_path) {
    .Call(`_StreamFind_rcpp_parse_asc_file`, file_path)
}

rcpp_write_asc_file <- function(file, metadata_list, spectra) {
    invisible(.Call(`_StreamFind_rcpp_write_asc_file`, file, metadata_list, spectra))
}

rcpp_streamcraft_decode_string <- function(base64_encoded) {
    .Call(`_StreamFind_rcpp_streamcraft_decode_string`, base64_encoded)
}

rcpp_streamcraft_encode_vector <- function(numeric_vector) {
    .Call(`_StreamFind_rcpp_streamcraft_encode_vector`, numeric_vector)
}

rcpp_streamcraft_parse_ms_analysis_from_files <- function(file_path) {
    .Call(`_StreamFind_rcpp_streamcraft_parse_ms_analysis_from_files`, file_path)
}

rcpp_streamcraft_parse_ms_spectra <- function(analysis, levels, targets, minIntensityMS1, minIntensityMS2) {
    .Call(`_StreamFind_rcpp_streamcraft_parse_ms_spectra`, analysis, levels, targets, minIntensityMS1, minIntensityMS2)
}

rcpp_streamcraft_parse_ms_chromatograms <- function(analysis, idx) {
    .Call(`_StreamFind_rcpp_streamcraft_parse_ms_chromatograms`, analysis, idx)
}

