# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_json_read_file <- function(file_path) {
    .Call(`_StreamFind_rcpp_json_read_file`, file_path)
}

rcpp_json_read_subtree <- function(file_path, path) {
    .Call(`_StreamFind_rcpp_json_read_subtree`, file_path, path)
}

rcpp_json_list_children <- function(file_path, path = "") {
    .Call(`_StreamFind_rcpp_json_list_children`, file_path, path)
}

rcpp_asm_read_file <- function(file_path) {
    .Call(`_StreamFind_rcpp_asm_read_file`, file_path)
}

rcpp_asm_index_table <- function(file_path) {
    .Call(`_StreamFind_rcpp_asm_index_table`, file_path)
}

rcpp_asm_read_subtree <- function(file_path, path) {
    .Call(`_StreamFind_rcpp_asm_read_subtree`, file_path, path)
}

rcpp_asm_read_primary_data <- function(file_path) {
    .Call(`_StreamFind_rcpp_asm_read_primary_data`, file_path)
}

rcpp_asm_list_children <- function(file_path, path = "") {
    .Call(`_StreamFind_rcpp_asm_list_children`, file_path, path)
}

rcpp_asm_validate_file <- function(json_file_path, schema_file, schema_root_dir = "") {
    .Call(`_StreamFind_rcpp_asm_validate_file`, json_file_path, schema_file, schema_root_dir)
}

duckdb_list_tables <- function(db_path) {
    .Call(`_StreamFind_duckdb_list_tables`, db_path)
}

duckdb_json_extension_info <- function(db_path) {
    .Call(`_StreamFind_duckdb_json_extension_info`, db_path)
}

rcpp_json_schema_validation_ok <- function() {
    .Call(`_StreamFind_rcpp_json_schema_validation_ok`)
}

rcpp_json_schema_validation_error <- function() {
    .Call(`_StreamFind_rcpp_json_schema_validation_error`)
}

rcpp_json_make_example <- function() {
    .Call(`_StreamFind_rcpp_json_make_example`)
}

rcpp_json_parse <- function(s) {
    .Call(`_StreamFind_rcpp_json_parse`, s)
}

#' Smooth chromatograms using moving-average or Savitzky-Golay filter
#'
#' @param chromatograms  data.frame with columns: analysis, replicate, index, id,
#'                       polarity, pre_mz, pre_ce, pro_mz, rt, intensity
#' @param method         "movingaverage" or "savgol"
#' @param window_size    window size (odd integer) for moving average
#' @param fl             filter length (odd) for SG
#' @param forder         polynomial order for SG
#' @param dorder         derivative order for SG (0 = smoothing)
#' @return data.frame with updated intensity column
rcpp_ms_smooth_chromatograms <- function(chromatograms, method = "movingaverage", window_size = 5L, fl = 11L, forder = 4L, dorder = 0L) {
    .Call(`_StreamFind_rcpp_ms_smooth_chromatograms`, chromatograms, method, window_size, fl, forder, dorder)
}

#' Correct chromatogram baselines using airPLS
#'
#' @param chromatograms  data.frame with at least: analysis, id, rt, intensity
#' @param lambda         smoothing penalty
#' @param differences    order of difference operator (1 or 2)
#' @param itermax        maximum iterations
#' @return data.frame with updated intensity, and added/updated baseline + raw columns
rcpp_ms_correct_baseline_airpls <- function(chromatograms, lambda = 10.0, differences = 1L, itermax = 20L) {
    .Call(`_StreamFind_rcpp_ms_correct_baseline_airpls`, chromatograms, lambda, differences, itermax)
}

#' Correct chromatogram baselines using Asymmetric Least Squares (ALS)
#'
#' @param chromatograms  data.frame with at least: analysis, id, rt, intensity
#' @param lambda         smoothing penalty
#' @param p              asymmetry parameter (0 < p < 0.5; typical 0.001–0.01)
#' @param maxit          maximum iterations
#' @return data.frame with updated intensity, and added/updated baseline + raw columns
rcpp_ms_correct_baseline_als <- function(chromatograms, lambda = 1e5, p = 0.001, maxit = 10L) {
    .Call(`_StreamFind_rcpp_ms_correct_baseline_als`, chromatograms, lambda, p, maxit)
}

#' Find chromatographic peaks using local-maxima method
#'
#' @param chromatograms  data.frame with analysis, replicate, index, id, polarity,
#'                       pre_mz, pre_ce, pro_mz, rt, intensity
#' @param min_height     minimum peak height
#' @param min_width      minimum peak width (rt units; 0 = no filter)
#' @param max_width      maximum peak width (rt units; 0 = no filter)
#' @return data.frame of peaks with schema matching MassSpecResults_Chromatograms Peaks table
rcpp_ms_find_chrom_peaks_local_maxima <- function(chromatograms, min_height = 0.0, min_width = 0.0, max_width = 0.0) {
    .Call(`_StreamFind_rcpp_ms_find_chrom_peaks_local_maxima`, chromatograms, min_height, min_width, max_width)
}

#' Find chromatographic peaks and integrate using pracma-style algorithm
#'
#' @param chromatograms       data.frame (same columns as above)
#' @param merge               merge close-by peaks?
#' @param close_by_threshold  merge distance in rt units
#' @param min_peak_height     minimum peak height
#' @param min_peak_distance   minimum distance between peaks (rt units)
#' @param min_peak_width      minimum peak width (rt units)
#' @param max_peak_width      maximum peak width (rt units)
#' @param min_sn              minimum signal-to-noise
#' @return data.frame of peaks
rcpp_ms_integrate_chromatograms <- function(chromatograms, merge = TRUE, close_by_threshold = 45.0, min_peak_height = 0.0, min_peak_distance = 10.0, min_peak_width = 5.0, max_peak_width = 120.0, min_sn = 10.0) {
    .Call(`_StreamFind_rcpp_ms_integrate_chromatograms`, chromatograms, merge, close_by_threshold, min_peak_height, min_peak_distance, min_peak_width, max_peak_width, min_sn)
}

#' Quantify peaks using OLS calibration
#'
#' Fits a polynomial (degree 1, 2 or 3) through the calibration points and
#' predicts concentration for all peaks using the fitted model.
#'
#' @param peaks          data.frame with at minimum: analysis, id, peak, area or intensity.
#'                       Calibration analyses must have a non-NA concentration column.
#' @param concentrations Named numeric vector: names = analysis names, values = concentration
#'                       (NA for unknowns).
#' @param value          "area" or "intensity" – which signal measure to fit against
#' @param model          "linear", "quadratic", or "cubic"
#' @return peaks data.frame with added column "concentration"
rcpp_ms_quantify_peaks_ols <- function(peaks, concentrations, value = "area", model = "linear") {
    .Call(`_StreamFind_rcpp_ms_quantify_peaks_ols`, peaks, concentrations, value, model)
}

#' Calculate charge states for mass spectra
#'
#' Groups input rows by (analysis, id), averages spectra across scans per group,
#' then calls the C++ charge-state algorithm.
#'
#' @param spectra     data.frame with: analysis, replicate, id, polarity, rt, mz, intensity
#' @param round_val   m/z rounding denominator for clustering (e.g. 35)
#' @param rel_low_cut relative intensity cut (fraction of base peak)
#' @param abs_low_cut absolute intensity cut
#' @param top_charges number of top anchor candidates
#' @return data.frame with columns: analysis, replicate, id, polarity, mz, intensity,
#'         cluster_mz, z, mass, rt
rcpp_ms_calculate_spectra_charges <- function(spectra, round_val = 35.0, rel_low_cut = 0.2, abs_low_cut = 300.0, top_charges = 5L) {
    .Call(`_StreamFind_rcpp_ms_calculate_spectra_charges`, spectra, round_val, rel_low_cut, abs_low_cut, top_charges)
}

#' Deconvolute charge-state spectra to neutral-mass spectra
#'
#' @param spectra   data.frame with: analysis, replicate, id, polarity, rt, mz, intensity
#' @param charges   data.frame from rcpp_ms_calculate_spectra_charges:
#'                  analysis, id, polarity, mz, z, cluster_mz, mass
#' @param clust_val mass clustering tolerance (Da)
#' @param window    m/z window around each charge to extract (half-width in m/z units)
#' @return data.frame with same schema as spectra but mz column replaced by mass
rcpp_ms_deconvolute_spectra <- function(spectra, charges, clust_val = 0.1, window = 20.0) {
    .Call(`_StreamFind_rcpp_ms_deconvolute_spectra`, spectra, charges, clust_val, window)
}

#' Find peaks/maxima in (deconvoluted) spectra
#'
#' Operates identically to rcpp_ms_find_chrom_peaks_local_maxima but on the
#' mass/intensity axis of spectra.
#'
#' @param spectra     data.frame with: analysis, replicate, id, polarity, rt, mass, intensity
#' @param min_height  minimum peak height
#' @param min_width   minimum width in mass units (0 = no filter)
#' @param max_width   maximum width in mass units (0 = no filter)
#' @return data.frame of spectral peaks
rcpp_ms_find_spectra_maxima <- function(spectra, min_height = 0.0, min_width = 0.0, max_width = 0.0) {
    .Call(`_StreamFind_rcpp_ms_find_spectra_maxima`, spectra, min_height, min_width, max_width)
}

rcpp_streamcraft_decode_string <- function(base64_encoded) {
    .Call(`_StreamFind_rcpp_streamcraft_decode_string`, base64_encoded)
}

rcpp_streamcraft_encode_vector <- function(numeric_vector) {
    .Call(`_StreamFind_rcpp_streamcraft_encode_vector`, numeric_vector)
}

rcpp_streamcraft_parse_ms_analysis_from_files <- function(file_path) {
    .Call(`_StreamFind_rcpp_streamcraft_parse_ms_analysis_from_files`, file_path)
}

rcpp_streamcraft_parse_ms_spectra <- function(analysis, levels, targets, minIntensityMS1, minIntensityMS2) {
    .Call(`_StreamFind_rcpp_streamcraft_parse_ms_spectra`, analysis, levels, targets, minIntensityMS1, minIntensityMS2)
}

rcpp_streamcraft_parse_ms_chromatograms <- function(analysis, idx) {
    .Call(`_StreamFind_rcpp_streamcraft_parse_ms_chromatograms`, analysis, idx)
}

rcpp_ms_cluster_spectra <- function(spectra, mzClust = 0.005, presence = 0.8, verbose = FALSE) {
    .Call(`_StreamFind_rcpp_ms_cluster_spectra`, spectra, mzClust, presence, verbose)
}

rcpp_nts_find_features <- function(info, spectra_headers, rtWindowsMin, rtWindowsMax, ppmThreshold = 15.0, noiseThreshold = 15.0, minSNR = 3.0, minTraces = 3L, baselineWindow = 200.0, maxWidth = 100.0, baseQuantile = 0.10, debugAnalysis = "", debugMZ = 0.0, debugSpecIdx = -1L) {
    .Call(`_StreamFind_rcpp_nts_find_features`, info, spectra_headers, rtWindowsMin, rtWindowsMax, ppmThreshold, noiseThreshold, minSNR, minTraces, baselineWindow, maxWidth, baseQuantile, debugAnalysis, debugMZ, debugSpecIdx)
}

rcpp_nts_load_features_ms1 <- function(info, spectra_headers, feature_list, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence) {
    .Call(`_StreamFind_rcpp_nts_load_features_ms1`, info, spectra_headers, feature_list, filtered, rtWindow, mzWindow, minTracesIntensity, mzClust, presence)
}

rcpp_nts_load_features_ms2 <- function(info, spectra_headers, feature_list, filtered, minTracesIntensity, isolationWindow, mzClust, presence) {
    .Call(`_StreamFind_rcpp_nts_load_features_ms2`, info, spectra_headers, feature_list, filtered, minTracesIntensity, isolationWindow, mzClust, presence)
}

rcpp_nts_create_components <- function(info, spectra_headers, feature_list, rtWindow, minCorrelation = 0.8, debugRT = 0.0, debugAnalysis = "") {
    .Call(`_StreamFind_rcpp_nts_create_components`, info, spectra_headers, feature_list, rtWindow, minCorrelation, debugRT, debugAnalysis)
}

rcpp_nts_annotate_components <- function(info, spectra_headers, feature_list, maxIsotopes = 5L, maxCharge = 1L, maxGaps = 1L, ppm = 10.0, debugComponent = "", debugAnalysis = "") {
    .Call(`_StreamFind_rcpp_nts_annotate_components`, info, spectra_headers, feature_list, maxIsotopes, maxCharge, maxGaps, ppm, debugComponent, debugAnalysis)
}

rcpp_nts_group_features <- function(info, spectra_headers, feature_list, method = "obi_warp", internal_standards_list = NULL, rtDeviation = 5.0, ppm = 5.0, minSamples = 1L, binSize = 5.0, debug = FALSE, debugRT = 0.0) {
    .Call(`_StreamFind_rcpp_nts_group_features`, info, spectra_headers, feature_list, method, internal_standards_list, rtDeviation, ppm, minSamples, binSize, debug, debugRT)
}

rcpp_nts_fill_features <- function(info, spectra_headers, feature_list, withinReplicate = FALSE, filtered = FALSE, rtExpand = 10.0, mzExpand = 0.01, maxPeakWidth = 30.0, minTracesIntensity = 1000.0, minNumberTraces = 5L, minIntensity = 5000.0, rtApexDeviation = 5.0, minSignalToNoiseRatio = 3.0, minGaussianFit = 0.2, debugFG = "") {
    .Call(`_StreamFind_rcpp_nts_fill_features`, info, spectra_headers, feature_list, withinReplicate, filtered, rtExpand, mzExpand, maxPeakWidth, minTracesIntensity, minNumberTraces, minIntensity, rtApexDeviation, minSignalToNoiseRatio, minGaussianFit, debugFG)
}

rcpp_nts_blank_subtraction <- function(info, spectra_headers, feature_list, blankThreshold = 5.0, rtExpand = 10.0, mzExpand = 0.005) {
    .Call(`_StreamFind_rcpp_nts_blank_subtraction`, info, spectra_headers, feature_list, blankThreshold, rtExpand, mzExpand)
}

rcpp_nts_filter_features <- function(info, feature_list, minSN = NA_real_, minIntensity = NA_real_, minArea = NA_real_, minWidth = NA_real_, maxWidth = NA_real_, maxPPM = NA_real_, minFwhmRT = NA_real_, maxFwhmRT = NA_real_, minFwhmMZ = NA_real_, maxFwhmMZ = NA_real_, minGaussianA = NA_real_, minGaussianMu = NA_real_, maxGaussianMu = NA_real_, minGaussianSigma = NA_real_, maxGaussianSigma = NA_real_, minGaussianR2 = NA_real_, maxJaggedness = NA_real_, minSharpness = NA_real_, minAsymmetry = NA_real_, maxAsymmetry = NA_real_, maxModality = NA_integer_, minPlates = NA_real_, onlyFilled = as.logical( c(NA_LOGICAL)), removeFilled = FALSE, minSizeEIC = NA_integer_, minSizeMS1 = NA_integer_, minSizeMS2 = NA_integer_, minRelPresenceReplicate = NA_real_, removeIsotopes = FALSE, removeAdducts = FALSE, removeLosses = FALSE) {
    .Call(`_StreamFind_rcpp_nts_filter_features`, info, feature_list, minSN, minIntensity, minArea, minWidth, maxWidth, maxPPM, minFwhmRT, maxFwhmRT, minFwhmMZ, maxFwhmMZ, minGaussianA, minGaussianMu, maxGaussianMu, minGaussianSigma, maxGaussianSigma, minGaussianR2, maxJaggedness, minSharpness, minAsymmetry, maxAsymmetry, maxModality, minPlates, onlyFilled, removeFilled, minSizeEIC, minSizeMS1, minSizeMS2, minRelPresenceReplicate, removeIsotopes, removeAdducts, removeLosses)
}

rcpp_nts_filter_suspects <- function(info, suspect_list, names = as.character( c()), minScore = NA_real_, maxErrorRT = NA_real_, maxErrorMass = NA_real_, idLevels = as.integer( c()), minSharedFragments = 0L, minCosineSimilarity = NA_real_) {
    .Call(`_StreamFind_rcpp_nts_filter_suspects`, info, suspect_list, names, minScore, maxErrorRT, maxErrorMass, idLevels, minSharedFragments, minCosineSimilarity)
}

rcpp_nts_filter_internal_standards <- function(info, internal_standards_list, names = as.character( c()), minScore = NA_real_, maxErrorRT = NA_real_, maxErrorMass = NA_real_, idLevels = as.integer( c()), minSharedFragments = 0L, minCosineSimilarity = NA_real_) {
    .Call(`_StreamFind_rcpp_nts_filter_internal_standards`, info, internal_standards_list, names, minScore, maxErrorRT, maxErrorMass, idLevels, minSharedFragments, minCosineSimilarity)
}

rcpp_nts_suspect_screening <- function(info, spectra_headers, feature_list, suspects, analyses = as.character( c("")), ppm = 5.0, sec = 10.0, ppmMS2 = 10.0, mzrMS2 = 0.008, minCosineSimilarity = 0.7, minSharedFragments = 3L, filtered = FALSE) {
    .Call(`_StreamFind_rcpp_nts_suspect_screening`, info, spectra_headers, feature_list, suspects, analyses, ppm, sec, ppmMS2, mzrMS2, minCosineSimilarity, minSharedFragments, filtered)
}

rcpp_nts_filter_features_ms2 <- function(info, feature_list, top = 0L, minIntensity = NA_real_, relMinIntensity = NA_real_, blankClean = FALSE, mzClust = 0.005, blankPresenceThreshold = 0.8, globalPresenceThreshold = 0.1) {
    .Call(`_StreamFind_rcpp_nts_filter_features_ms2`, info, feature_list, top, minIntensity, relMinIntensity, blankClean, mzClust, blankPresenceThreshold, globalPresenceThreshold)
}

rcpp_nts_metfrag_screening <- function(info, spectra_headers, feature_list, metfrag_path, database_type = "LocalCSV", database_path = "", analyses = as.character( c("")), ppm = 5.0, sec = 10.0, ppmMS2 = 10.0, mzrMS2 = 0.008, top_n = 1L, filtered = FALSE, java_path = "java", run_dir = "", debug = FALSE, extra_params = NULL) {
    .Call(`_StreamFind_rcpp_nts_metfrag_screening`, info, spectra_headers, feature_list, metfrag_path, database_type, database_path, analyses, ppm, sec, ppmMS2, mzrMS2, top_n, filtered, java_path, run_dir, debug, extra_params)
}

rcpp_nts_assign_transformation_products <- function(suspects, transformation_products, chromatographic_phase = "reverse_phase", mzrMS2 = 0.008) {
    .Call(`_StreamFind_rcpp_nts_assign_transformation_products`, suspects, transformation_products, chromatographic_phase, mzrMS2)
}

rcpp_project_new <- function(db_path, project_id) {
    .Call(`_StreamFind_rcpp_project_new`, db_path, project_id)
}

rcpp_project_copy <- function(project_xptr, db_path, project_id) {
    .Call(`_StreamFind_rcpp_project_copy`, project_xptr, db_path, project_id)
}

rcpp_project_validate <- function(project_xptr) {
    invisible(.Call(`_StreamFind_rcpp_project_validate`, project_xptr))
}

rcpp_project_get_metadata <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_metadata`, project_xptr)
}

rcpp_project_set_metadata <- function(project_xptr, metadata_json) {
    invisible(.Call(`_StreamFind_rcpp_project_set_metadata`, project_xptr, metadata_json))
}

rcpp_project_get_workflow <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_workflow`, project_xptr)
}

rcpp_project_set_workflow <- function(project_xptr, workflow_json) {
    invisible(.Call(`_StreamFind_rcpp_project_set_workflow`, project_xptr, workflow_json))
}

rcpp_project_list_tables <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_list_tables`, project_xptr)
}

rcpp_project_get_audit <- function(project_xptr) {
    .Call(`_StreamFind_rcpp_project_get_audit`, project_xptr)
}

